### ISSUE TITLE
borg config --list

### ISSUE THREAD

**Issue by SanskritFritz** [milkey-mouse/borg#1]
Could we have a `-l --list` option to list all available keys for `borg config`?

**Comment by twilligon** [comment]
You could put whatever keys you want in the config, and any unrelated to Borg are just left alone. Listing all options that Borg actually cares about would take a lot of refactoring.
Is this for the autocomplete? In that case, it would be easy to list the keys currently in the config file.

**Comment by SanskritFritz** [comment]
Oh, OK. So, the config file is in the repository. Allright then, sorry for the noise.
Just one more question, how do I find the config if --cache is used?

**Comment by twilligon** [comment]
The cache config file is in the repo's cache dir:

    $ borg info /path/to/repo | grep Cache
    Cache: /home/milkey/.cache/borg/ebc6f0f0c7423dfe43a6c12cbc77ac4039b7642fcb92f0b46f1fe27663951c18

If you don't want to run `borg info` just for that:

https://github.com/milkey-mouse/borg/blob/c0b905875953a3819cb8b1454d3985608dff1934/src/borg/helpers/fs.py#L50-L53

Essentially, it will be `$BORG_CACHE_DIR/$(borg config /path/to/repo id)/config`, or `$XDG_CACHE_HOME/$(borg config /path/to/repo id)/config` if that doesn't exist, or `~/.cache/$(borg config /path/to/repo id)/config` if none of the others exist.
